name: Import blocklists

on:
  push:
    paths:
      - 'sources/imports/**.txt'
  schedule:
    - cron:  '42 3,15 * * *'
  workflow_dispatch:

jobs:
  import:
    name: Import blocklists

    runs-on: ubuntu-slim

    steps:
    - uses: actions/checkout@v6
    - name: Set up Python
      uses: actions/setup-python@v6
    - name: Run import
      run: ./scripts/import.sh
    - name: Run update
      run: ./scripts/update.sh
    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Import blocklists"
        git push
