name: Update blocklists

on:
  push:
    paths:
      - 'sources/**.txt'
      - '!sources/imports/**'
  workflow_dispatch:

jobs:
  update:
    name: Update blocklists

    runs-on: ubuntu-slim

    steps:
    - uses: actions/checkout@v6
    - name: Set up Python
      uses: actions/setup-python@v6
    - name: Run update
      run: ./scripts/update.sh
    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Update blocklists"
        git push
